services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
      # target: base
#      swap below for multistage build that has scss compilation
#         inline with development server
      dockerfile: Dockerfile.multistage
      target: development
      args:
        - DEV=true
    ports:
      - "8000:8000"
#    environment:
#      - PORT=8000
    volumes:
      - ./app:/app
    command: |
      sh -c "
      /scripts/migrate.sh
      /scripts/fixtures.sh
      /scripts/collectstatic.sh
      # /scripts/entrypoint.sh
      (npm run compile:sass & /scripts/entrypoint.sh)
      "
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  dev-db-data: