services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  dev-db-data: