# Generated by Django 5.1.5 on 2025-01-29 19:27

import core.models.blog
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='max length 60 characters', max_length=60)),
                ('description', models.CharField(blank=True, help_text='recommended length 160 charaters (max 255)', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=core.models.blog.cover_image_file_path)),
                ('cover_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='title is used if blank (max 60 characters)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='description is used if blank (keep below 160, max 255)', max_length=255)),
                ('slug', models.SlugField(blank=True, db_index=False, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(through='core.PostAuthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
